/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Game game = new Game();
        game.roll(0);
        System.out.println(game.score());
    }
}
